docs_dir: content
edit_uri: https://github.com/thedemons/opentele/tree/main/docs/content
extra_css:
- stylesheets/extra.css
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- meta
- md_in_html
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
nav:
- Home: README.md
- TDesktop:
  - Account: tdesktop/account.md
  - AuthKey: tdesktop/authkey.md
repo_url: https://github.com/thedemons/opentele
site_name: OpenTele
theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
