docs_dir: content
edit_uri: https://github.com/thedemons/opentele/tree/main/docs/content
extra_css:
- assets/pymdownx-extras/extra-c12baed3e0.css
extra_javascript:
- https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
- assets/pymdownx-extras/extra-loader-9e2c67b9.js
markdown_extensions:
- markdown.extensions.toc: null
- markdown.extensions.admonition: null
- markdown.extensions.smarty:
    smart_quotes: false
- pymdownx.betterem: null
- markdown.extensions.attr_list: null
- markdown.extensions.def_list: null
- markdown.extensions.tables: null
- markdown.extensions.abbr: null
- markdown.extensions.footnotes: null
- markdown.extensions.md_in_html: null
- pymdownx.superfences:
    preserve_tabs: true
- pymdownx.snippets: null
- pymdownx.highlight:
    extend_pygments_lang:
    - lang: python
      name: python
      options:
        python3: true
    - lang: python
      name: pyinline
      options:
        python3: true
        startinline: true
    linenums_style: pymdownx-inline
    pygments_style: material
    use_pygments: true
- pymdownx.inlinehilite: null
- pymdownx.magiclink:
    normalize_issue_symbols: true
    repo: opentele
    repo_url_shortener: true
    repo_url_shorthand: true
    social_url_shortener: true
    social_url_shorthand: true
    user: thedemons
- pymdownx.tilde: null
- pymdownx.caret: null
- pymdownx.smartsymbols: null
- pymdownx.emoji: null
- pymdownx.escapeall:
    hardbreak: true
    nbsp: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.progressbar: null
- pymdownx.arithmatex:
    block_tag: pre
    generic: true
- pymdownx.mark: null
- pymdownx.striphtml: null
- pymdownx.details: null
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.saneheaders: null
nav:
- Home:
  - OpenTele: home/README.md
- API Documentation:
  - Telethon:
    - TelegramClient: api-documentation/telethon/telegramclient.md
  - Authorization:
    - APIData: api-documentation/authorization/apidata.md
    - APITemplate: api-documentation/authorization/apitemplate.md
  - Telegram Desktop:
    - TDesktop: api-documentation/telegram-desktop/tdesktop.md
    - Account: api-documentation/telegram-desktop/account.md
    - AuthKey: api-documentation/telegram-desktop/authkey.md
    - MTP: api-documentation/telegram-desktop/mtp.md
  - Exceptions: api-documentation/exceptions.md
repo_url: https://github.com/thedemons/opentele
site_author: thedemons
site_description: A python library created to make life easier for Telegram API Developers.
site_name: OpenTele
theme:
  custom_dir: theme
  features:
  - navigation.tabs
  - navigation.top
  - navigation.instant
  font:
    code: Monaco Mono
    text: Monaco
  icon:
    logo: material/book-open-page-variant
  name: material
  palette:
    accent: deep purple
    primary: light blue
    scheme: dracula
