docs_dir: content
edit_uri: https://github.com/thedemons/opentele/tree/main/docs/content
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- meta
- md_in_html
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.highlight:
    anchor_linenums: true
    noclasses: true
    pygments_style: one-dark
    use_pygments: true
- pymdownx.superfences
nav:
- Home: README.md
- TDesktop:
  - TelegramClient: tdesktop/telegramclient.md
  - Account: tdesktop/account.md
  - AuthKey: tdesktop/authkey.md
  - MTP: tdesktop/mtp.md
- APIData: apidata.md
- Exceptions: exceptions.md
repo_url: https://github.com/thedemons/opentele
site_author: thedemons
site_description: A python library created to make life easier for Telegram API Developers.
site_name: OpenTele
theme:
  name: material
  palette:
  - accent: purple
    primary: light blue
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - accent: purple
    primary: blue
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
