docs_dir: content
edit_uri: https://github.com/thedemons/opentele/tree/main/docs/content
markdown_extensions:
- admonition
- abbr
- attr_list
- def_list
- footnotes
- meta
- md_in_html
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.emoji
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    repo: opentele
    repo_url_shorthand: true
    user: thedemons
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- Home: README.md
- TDesktop:
  - TelegramClient: tdesktop/telegramclient.md
  - Account: tdesktop/account.md
  - AuthKey: tdesktop/authkey.md
  - MTP: tdesktop/mtp.md
- APIData: apidata.md
- Exceptions: exceptions.md
repo_url: https://github.com/thedemons/opentele
site_author: thedemons
site_description: A python library created to make life easier for Telegram API Developers.
site_name: OpenTele
theme:
  name: material
  palette:
  - accent: purple
    primary: light blue
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - accent: purple
    primary: blue
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
